version: '3'
services:
  packet-forwarder:
    image: hm-pktfwd:latest
    restart: always
    privileged: true
    network_mode: host
    environment:
      - FIRMWARE_VERSION=2022.01.29.0-8
      - VARIANT=NEBHNT-HHRK4
      - LOGLEVEL=DEBUG
    volumes:
      - /var/pktfwd:/var/pktfwd
    devices:
      - "/dev/spidev0.0:/dev/spidev32766.0"

